base_url = "https://ayushjayaswal.xyz/blog"
title = "porceylain's Blogs"
description = "Writings and posts from porceylain"
default_language = "en"
compile_sass = true
build_search_index = false

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
smart_punctuation = true

[extra]
show_tags = true
posts_per_page = 10
